/**
 * Locale integrity + the translate() helper.
 *
 * No key and no network: the message files already exist, generated by
 * `npm run i18n` before the build.
 */
import { translate, isLocale, LOCALES } from '../lib/i18n'
import en from '../../messages/en.json'
import es from '../../messages/es.json'
import fr from '../../messages/fr.json'
import de from '../../messages/de.json'

const LOCALE_FILES = { es, fr, de }

const flatten = (obj, prefix = '') =>
  Object.entries(obj).reduce((acc, [k, v]) => {
    const key = prefix ? `${prefix}.${k}` : k
    return v && typeof v === 'object' ? { ...acc, ...flatten(v, key) } : { ...acc, [key]: v }
  }, {})

const PLACEHOLDERS = /(\{\{\w+\}\})/g
const phIn = (s) => (typeof s === 'string' ? (s.match(PLACEHOLDERS) || []).sort() : [])
const enFlat = flatten(en)

describe.each(Object.keys(LOCALE_FILES))('%s messages', (lang) => {
  const flat = flatten(LOCALE_FILES[lang])

  it('has the same keys as en', () => {
    expect(Object.keys(flat).sort()).toEqual(Object.keys(enFlat).sort())
  })

  it('preserves every placeholder', () => {
    for (const [key, value] of Object.entries(enFlat)) {
      if (!phIn(value).length) continue
      expect(phIn(flat[key])).toEqual(phIn(value))
    }
  })

  it('keeps both plural forms', () => {
    expect(flat['home.tasks_one']).toBeTruthy()
    expect(flat['home.tasks_other']).toBeTruthy()
  })
})

describe('translate', () => {
  it('resolves a dotted key', () => {
    expect(translate(en, 'actions.save')).toBe('Save changes')
  })

  it('substitutes named placeholders', () => {
    expect(translate(en, 'home.greeting', { name: 'Ada' })).toBe('Welcome back, Ada!')
  })

  it('selects the singular form for count 1', () => {
    expect(translate(en, 'home.tasks', { count: 1 })).toBe('You have 1 open task')
  })

  it('selects the plural form for other counts', () => {
    expect(translate(en, 'home.tasks', { count: 4 })).toBe('You have 4 open tasks')
  })

  it('selects the right plural form in Spanish too', () => {
    expect(translate(es, 'home.tasks', { count: 1 })).toContain('1')
    expect(translate(es, 'home.tasks', { count: 4 })).not.toBe(translate(es, 'home.tasks', { count: 1 }))
  })

  it('returns the key when a message is missing, so misses are visible', () => {
    expect(translate(en, 'nope.missing')).toBe('nope.missing')
  })

  it('leaves an unknown placeholder untouched rather than printing undefined', () => {
    expect(translate(en, 'home.greeting', {})).toBe('Welcome back, {{name}}!')
  })
})

describe('isLocale', () => {
  it('accepts supported locales and rejects others', () => {
    for (const l of LOCALES) expect(isLocale(l)).toBe(true)
    expect(isLocale('xx')).toBe(false)
    expect(isLocale(undefined)).toBe(false)
  })
})
